### ISSUE TITLE
[OpenApi] ref で定義したものが def-{count} になる

### ISSUE THREAD

**Issue by takeruun** [takeruun/fastify-sample#2]
# Problem

下記 `ref` が
```
{
  $id: 'user',
  type: 'object',
  properties: {
    id: { type: 'string' },
    name: { type: 'string' },
  },
}
```

yml 上では下記で出力される
```
components:
  schemas:
    def-0:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      title: user
```

# Solution
swagger 生成に下記を指定する。
```
refResolver: {
  buildLocalReference: (json, _baseUri, _fragment, _i) => {
    return json.$id;
  },
},
```
公式GIthub：https://github.com/fastify/fastify-swagger#register.options.refResolver
